Create Signup Screen UI
cemdemir-dev/CactusNotes pull request #2
Opened 2021-04-14 11:13 UTC by cemdemir-dev

This PR adds Signup screen and Signup validations.

2021-04-14 19:01 UTC, safaorhan requested changes
Congratz for the first ever PR! 🥳 

If you can address my comments we can take a second look together!

2021-04-15 14:01 UTC, cemdemir-dev commented on app/src/main/AndroidManifest.xml
> +        android:label="Sign up"
Done!

2021-04-15 14:01 UTC, cemdemir-dev commented on app/src/main/java/com/example/cactusnotes/SignupActivity.kt
> +    fun Char.isSpecial() = (!isDigit() && !isLetter())
Done!

2021-04-15 14:01 UTC, cemdemir-dev commented on app/src/main/java/com/example/cactusnotes/SignupActivity.kt
> +    fun String.containsSpecChar() = any { it.isSpecial() }
Done!

2021-04-15 14:01 UTC, cemdemir-dev commented on app/src/main/java/com/example/cactusnotes/SignupActivity.kt
> +                    binding.passwordInputLayout.error = getString(R.string.password_special_char)
Done!

2021-04-15 14:03 UTC, cemdemir-dev commented on app/src/main/java/com/example/cactusnotes/SignupActivity.kt
> +                !email.contains("@") && (!email.contains(".")) -> {
Done!

2021-04-15 14:04 UTC, cemdemir-dev commented on app/src/main/java/com/example/cactusnotes/SignupActivity.kt
> +                !username.all { it.isLowerCase() || it.isDigit() || username.contains("_") } -> {
Done!

2021-04-15 14:04 UTC, cemdemir-dev commented on app/src/main/res/layout/activity_signup.xml
> +    android:padding="18dp"
Done!

2021-04-15 14:04 UTC, cemdemir-dev commented on app/src/main/res/layout/activity_signup.xml
> +    <com.google.android.material.textfield.TextInputLayout
Done!

2021-04-15 14:05 UTC, cemdemir-dev commented on app/src/main/java/com/example/cactusnotes/SignupActivity.kt
> +            when {
Done!

2021-04-19 18:33 UTC, merged